[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "neutrophil_shape"
version = "1.0.0"
description = "Analyze motile neutrophil morphology"
dependencies = [
]
authors = [
    {name = "Aaron van Loon", email = "apvl92@uw.edu"},
]
# readme = "README.rst"

[tool.setuptools.packages.find]
include = ["neutrophil_shape*"]