
[common]
smooth_factor = 5 #trajectory smoothness
sigma = 0 #gaussian smooth for mesh 
l_order = 10 # SH order
npcs = 8 # number of principal components to keep
pilr_method = 'none' #what kind of PILR signal to calculate 'none','threshold','raw'
nisos = [1,63] # interpolated "shells" if calculated a PILR

[im_params.confocal]
xyres = 0.3394 #um / pixel
zstep = 0.7 #um
time_interval = 10 #sec/frame
xy_buffer = 20 #xy pixel buffer for cropping cells
z_buffer = 10 #zpixel buffer for cropping cells
stackshape = [150,1024,1024] # zyx size of single timepoints
whatseg = 'hl60' #what segmentation function to use for the membrane

[im_params.lls]
xyres = 0.145 #um / pixel
zstep = 0.145 #um / pixel
time_interval = 5 #sec/frame
decon = true #whether the images to be segmented are deconvolved
orig_size = false #whether to leave "cropped" images in their original shape
xy_buffer = 25 #xy pixel buffer for cropping cells
z_buffer = 25 #z pixel buffer for cropping cells
hilo = true #whether or not to do multiple thresholds for segmenting secondary signals

[db_params.confocal]
nbins = 15 #number of bins to use for the CGPSs
ntrans = 1 #number of consecutive transitions to sample when bootstrapping
bsiter = 3000 #number of bootstrap iterations
ttot = 1800 #total time of to bootstrap in seconds
[db_params.confocal.all_origins]
shape = [[8,8],[8,8],[8,8],[8,8],[8,7],[8,8],[8,8],
            [8,8],[8,7],[8,8],[8,8],[8,8],[8,8],
                [7,8],[6,8],[8,8],[8,8],[7,9],
                    [8,8],[8,8],[8,8],[8,8],
                        [8,8],[8,8],[8,8],
                            [8,8],[8,8],
                                [8,8]]
trajectory_shape = [[8,8],[8,8],[9,8],[8,8],[9,7],[9,8],[9,8],
                        [8,8],[8,8],[8,8],[8,8],[8,8],[8,8],
                            [8,8],[8,8],[8,8],[8,8],[8,8],
                                [8,8],[8,8],[8,8],[8,8],
                                    [8,8],[8,8],[8,8],
                                        [6,8],[8,8],
                                            [8,8]]
trajectory = [[7,8],[8,6],[8,7],[8,8],[8,8],[8,8],[9,8],
                [8,6],[8,7],[8,8],[8,7],[8,8],[8,8],
                    [8,8],[7,8],[8,8],[8,8],[9,8],
                        [7,8],[9,8],[8,8],[8,8],
                            [8,8],[8,8],[9,8],
                                [8,7],[8,8],
                                    [8,8]]


[db_params.lls]
nbins = 15 #number of bins to use for the CGPSs
ntrans = 1 #number of consecutive transitions to sample when bootstrapping
bsiter = 3000 #number of bootstrap iterations
ttot = 3600 #total time of to bootstrap in seconds
[db_params.lls.all_origins]
trajectory = [[9,10],[8,6],[8,9],[8,8],[8,8],[8,8],[9,7],
                [8,6],[8,9],[8,8],[8,7],[8,7],[8,8],
                    [8,8],[7,8],[8,8],[8,8],[9,8],
                        [9,8],[7,8],[8,8],[8,8],
                            [8,8],[8,8],[8,8],
                                [8,7],[8,8],
                                    [8,8]]



[galv]
serverdir = '//10.158.28.37/ExpansionHomesA/avlnas/HL60 Galv/'
localdir = 'E:/Aaron/Galvanotaxis_Confocal_40x_37C_10s_test/'
dates = ['20231116','20231122']

[ck666]
serverdir = '//10.158.28.37/ExpansionHomesA/avlnas/HL60 CK666/'
localdir = 'E:/Aaron/CK666_Confocal_40x_37C_test/'
dates = ['20240610','20240617','20240620','20241205','20241209']

[pnb]
serverdir = '//10.158.28.37/ExpansionHomesA/avlnas/HL60 ParaNitroBlebbistatin/'
localdir = 'E:/Aaron/ParaNitroBlebbistatin_Confocal_40x_37C_test/'
dates = ['20240624','20240626','20240701','20241125','20241126','20241127']

[dependencies]
conda = [
    "python=3.12",
    "pip",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "scikit-image",
    "matplotlib",
    "vtk",
    "seaborn",
    "tifffile",
    "aicspylibczi",
    "bottleneck",
    "pyarrow",
    "pyshtools",
    "conda-lock",
    "scikit-posthocs",
    "statsmodels",
]
pip = [
    # "pyshtools==4.14",
    # "aicssegmentation",
]
