name: nsa
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pip
- numpy
- pandas
- scipy
- scikit-learn
- scikit-image
- matplotlib
- vtk
- seaborn
- tifffile
- aicspylibczi
- bottleneck
- pyarrow
- pyshtools
- conda-lock
- pip: []
