name: nsa
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pip
- conda-lock
- ipykernel
- numpy
- pandas
- scipy
- scikit-learn
- scikit-image
- matplotlib
- seaborn
- pyvista
- vtk
- tifffile
- aicspylibczi
- bottleneck
- pyarrow
- pyshtools
- scikit-posthocs
- statsmodels
- pip: []
