name: nsa_env
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pip
- numpy
- pandas
- scipy
- scikit-learn
- matplotlib
- vtk
- scikit-image
- seaborn
- tifffile
- aicspylibczi
- bottleneck
- pyarrow
- opencv
- pyshtools
- pip: []
